{% set name = "objexplore" %}
{% set version = "1.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/objexplore-{{ version }}.tar.gz
  sha256: 8298ea17d66084b3ad6e04239da19d7051f2a80669b5c0118f7fb9b854ba6370

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - blessed ==1.17.12
    - pip
    - python {{ python_min }}
    - rich ==10.9.0
    - setuptools
  run:
    - blessed ==1.17.12
    - python >={{ python_min }}
    - rich ==10.9.0

test:
  imports:
    - objexplore
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/kylepollina/objexplore
  summary: Interactive Python Object Explorer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
