{% set name = "objexplore" %}
{% set version = "1.5.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/objexplore-{{ version }}.tar.gz
  sha256: edbfdfd5b3078d6bd5af7e4146848b561a8156baee5997e3f97914657660a38f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - blessed ==1.17.12
    - pip
    - python >=3.7
    - rich ==10.9.0
  run:
    - blessed ==1.17.12
    - python >=3.7
    - rich ==10.9.0

test:
  imports:
    - objexplore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/kylepollina/objexplore
  summary: Interactive Python Object Explorer
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
